### ISSUE TITLE
Can you provide some example with react-redux?

### ISSUE THREAD

**Issue by xgrommx** [jas-chen/rx-redux#3]
Hello @jas-chen. Can you provide some example with https://github.com/gaearon/react-redux?

**Comment by jas-chen** [comment]
Hello @xgrommx, I haven't make sure it works yet, but since rx-redux implemented all of the redux APIs, I think it will work naturally. Let me know if you encounter any problem while getting them work together.

The reactive way to combine react and rx-redux is working in progress, I think I need to take a look at [cycle-react](https://github.com/pH200/cycle-react)'s source code to get some idea.

**Comment by xgrommx** [comment]
@jas-chen I tried use official example https://github.com/gaearon/redux/tree/breaking-changes-1.0/examples/counter with rx-redux instead of redux but this example doesn't work with rx-redux.

**Comment by xgrommx** [comment]
Compare this https://github.com/gaearon/redux/blob/breaking-changes-1.0/src/index.js#L7 and this https://github.com/jas-chen/rx-redux/blob/master/src/index.js#L7. Also this https://github.com/gaearon/redux/blob/breaking-changes-1.0/src/createStore.js#L130 and this https://github.com/jas-chen/rx-redux/blob/master/src/createStore.js#L44. Also interesting this commit https://github.com/gaearon/redux/commit/d92f08e804a8b2f91d7f77a8bb10ee1c279cee6a

**Comment by jas-chen** [comment]
Will keep working on this issue next day, thanks for the info!

**Comment by xgrommx** [comment]
@jas-chen Also I'll look on this problem today but later.

**Comment by jas-chen** [comment]
@xgrommx I just provide an example, [check it out](https://github.com/jas-chen/rx-redux/tree/master/examples/counter-react-redux)!

**Comment by xgrommx** [comment]
@jas-chen Without an additional subscription this code doesn't work? I mean the same like in original Redux.

**Comment by xgrommx** [comment]
I see you have a new approach for middlewares?) Difference between an original middleware and reactive middleware just don't to use `dispatch`?

**Comment by jas-chen** [comment]
@xgrommx I think this is because `state$` is a [cold observable](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/creating.md#Cold vs. Hot Observables), it start running upon subscription, so we have to call subscribe().

What if rx-redux call subscribe() for you? The initial state will be published immediately and you can't get it when you subscribe to state$ later.

**Comment by jas-chen** [comment]
In this case `react-redux` will not subscribe to `state$`, so you can call subscribe() right after createStore if you don't want to modify App component.

**Comment by jas-chen** [comment]
I updated the example, moved it out.

**Comment by xgrommx** [comment]
Hot observable can be get with `publish().refCount()` or `publishValue(v).refCount()`

**Comment by jas-chen** [comment]
@xgrommx thank you! Check out v0.5.2 and updated version react-redux example.
Awesome 👍!

**Comment by jas-chen** [comment]
@xgrommx, see universal example, it shows how you can benefited from using RxMiddleware.

**Comment by xgrommx** [comment]
@jas-chen Thanks! Also look at this method http://xgrommx.github.io/rx-book/content/observable/observable_instance_methods/connect.html which give able create a hot observable.
