### ISSUE TITLE
有类似于react-redux 这样的包可用么？

### ISSUE THREAD

**Issue by anlijiu** [jas-chen/rx-redux#5]
弱弱的问下有UI绑定的包 或者 best practice 可用么？

**Comment by jas-chen** [comment]
@anlijiu 你好，

The concept of reactive programming is that everything is observable, so I don't recommend using `react-redux` because it injects dispatcher and model into view.

The best practice is, propagate intents from components as streams and gather them to be `intent$` and connect `intent$` to `rx-redux`. This will make your view layer clean, without any model or dispatcher code.

To implement such component, you can pass a Rx.Subject as attribute, for example, let's name it `clickEvent$`, and you call `this.props.clickEvent$.onNext({intent: 'click'})` inside your component, and in parent component you can subscribe `clickEvent$` and propagate another intent to it's parent component and so on. Finally, at top-level component(App) you will have a `intent$` to use.
